language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - bash .travis/setup_lua.sh
  - sudo luarocks install lunitx
  - wget http://curl.haxx.se/download/curl-7.37.0.tar.gz
  - tar -xzf curl-7.37.0.tar.gz
  - cd curl-7.37.0/
  - ./configure
  - make
  - sudo make install
  - cd ..
  - sudo pip install cpp-coveralls

install:
  - sudo luarocks make rockspecs/lcurl-scm-0.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

script: 
  - cd test
  - lunit.sh run.lua

after_success:
  - coveralls -b .. -r ..

notifications:
  email:
    on_success: change
    on_failure: always
